// protoc-gen-luau/luauoptions/luau_options.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: luauoptions/luau_options.proto

package luauoptions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_luauoptions_luau_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51000,
		Name:          "luau.luau_generator",
		Tag:           "bytes,51000,opt,name=luau_generator",
		Filename:      "luauoptions/luau_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51001,
		Name:          "luau.luau_data_types_require",
		Tag:           "bytes,51001,opt,name=luau_data_types_require",
		Filename:      "luauoptions/luau_options.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// Which generator strategy to use: "data_types" | "schema"
	//
	// optional string luau_generator = 51000;
	E_LuauGenerator = &file_luauoptions_luau_options_proto_extTypes[0]
	// Override the require path for data_types import.
	// Default: "@lib/data_types"
	//
	// optional string luau_data_types_require = 51001;
	E_LuauDataTypesRequire = &file_luauoptions_luau_options_proto_extTypes[1]
)

var File_luauoptions_luau_options_proto protoreflect.FileDescriptor

const file_luauoptions_luau_options_proto_rawDesc = "" +
	"\n" +
	"\x1eluauoptions/luau_options.proto\x12\x04luau\x1a google/protobuf/descriptor.proto:E\n" +
	"\x0eluau_generator\x12\x1c.google.protobuf.FileOptions\x18\xb8\x8e\x03 \x01(\tR\rluauGenerator:U\n" +
	"\x17luau_data_types_require\x12\x1c.google.protobuf.FileOptions\x18\xb9\x8e\x03 \x01(\tR\x14luauDataTypesRequireB\x1dZ\x1bprotoc-gen-luau/luauoptionsb\x06proto3"

var file_luauoptions_luau_options_proto_goTypes = []any{
	(*descriptorpb.FileOptions)(nil), // 0: google.protobuf.FileOptions
}
var file_luauoptions_luau_options_proto_depIdxs = []int32{
	0, // 0: luau.luau_generator:extendee -> google.protobuf.FileOptions
	0, // 1: luau.luau_data_types_require:extendee -> google.protobuf.FileOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_luauoptions_luau_options_proto_init() }
func file_luauoptions_luau_options_proto_init() {
	if File_luauoptions_luau_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_luauoptions_luau_options_proto_rawDesc), len(file_luauoptions_luau_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_luauoptions_luau_options_proto_goTypes,
		DependencyIndexes: file_luauoptions_luau_options_proto_depIdxs,
		ExtensionInfos:    file_luauoptions_luau_options_proto_extTypes,
	}.Build()
	File_luauoptions_luau_options_proto = out.File
	file_luauoptions_luau_options_proto_goTypes = nil
	file_luauoptions_luau_options_proto_depIdxs = nil
}
