// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mappingoptions/mapping_options.proto

package mappingoptions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_mappingoptions_mapping_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         52000,
		Name:          "luau.source",
		Tag:           "bytes,52000,opt,name=source",
		Filename:      "mappingoptions/mapping_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         52001,
		Name:          "luau.target",
		Tag:           "bytes,52001,opt,name=target",
		Filename:      "mappingoptions/mapping_options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string source = 52000;
	E_Source = &file_mappingoptions_mapping_options_proto_extTypes[0]
	// optional string target = 52001;
	E_Target = &file_mappingoptions_mapping_options_proto_extTypes[1]
)

var File_mappingoptions_mapping_options_proto protoreflect.FileDescriptor

const file_mappingoptions_mapping_options_proto_rawDesc = "" +
	"\n" +
	"$mappingoptions/mapping_options.proto\x12\x04luau\x1a google/protobuf/descriptor.proto:7\n" +
	"\x06source\x12\x1d.google.protobuf.FieldOptions\x18\xa0\x96\x03 \x01(\tR\x06source:7\n" +
	"\x06target\x12\x1d.google.protobuf.FieldOptions\x18\xa1\x96\x03 \x01(\tR\x06targetB Z\x1eprotoc-gen-luau/mappingoptionsb\x06proto3"

var file_mappingoptions_mapping_options_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_mappingoptions_mapping_options_proto_depIdxs = []int32{
	0, // 0: luau.source:extendee -> google.protobuf.FieldOptions
	0, // 1: luau.target:extendee -> google.protobuf.FieldOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mappingoptions_mapping_options_proto_init() }
func file_mappingoptions_mapping_options_proto_init() {
	if File_mappingoptions_mapping_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mappingoptions_mapping_options_proto_rawDesc), len(file_mappingoptions_mapping_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_mappingoptions_mapping_options_proto_goTypes,
		DependencyIndexes: file_mappingoptions_mapping_options_proto_depIdxs,
		ExtensionInfos:    file_mappingoptions_mapping_options_proto_extTypes,
	}.Build()
	File_mappingoptions_mapping_options_proto = out.File
	file_mappingoptions_mapping_options_proto_goTypes = nil
	file_mappingoptions_mapping_options_proto_depIdxs = nil
}
