package main

import (
	"path"
	"strings"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"

	"protoc-gen-luau/mappingoptions"
)

// mappingField represents a single source or target field in a mapping rule.
type mappingField struct {
	fieldName string   // camelCase local variable name (from proto field name)
	rawPath   string   // original annotation value e.g. "master.some_field"
	pathParts []string // split by ".", each part converted to camelCase
	isSource  bool
}

// mappingRule represents one proto message that defines a mapping rule.
type mappingRule struct {
	messageName string
	sources     []mappingField
	targets     []mappingField
}

// parseMappingRules extracts mapping rules from all messages in the file.
func parseMappingRules(file *protogen.File) []mappingRule {
	var rules []mappingRule
	for _, msg := range file.Messages {
		rule := mappingRule{
			messageName: msg.GoIdent.GoName,
		}
		for _, field := range msg.Fields {
			opts := field.Desc.Options()
			if opts == nil {
				continue
			}
			if proto.HasExtension(opts, mappingoptions.E_Source) {
				rawPath := proto.GetExtension(opts, mappingoptions.E_Source).(string)
				mf := parseMappingField(field, rawPath, true)
				rule.sources = append(rule.sources, mf)
			}
			if proto.HasExtension(opts, mappingoptions.E_Target) {
				rawPath := proto.GetExtension(opts, mappingoptions.E_Target).(string)
				mf := parseMappingField(field, rawPath, false)
				rule.targets = append(rule.targets, mf)
			}
		}
		if len(rule.sources) > 0 || len(rule.targets) > 0 {
			rules = append(rules, rule)
		}
	}
	return rules
}

// parseMappingField converts a proto field + raw annotation path into a mappingField.
func parseMappingField(field *protogen.Field, rawPath string, isSource bool) mappingField {
	parts := strings.Split(rawPath, ".")
	camelParts := make([]string, len(parts))
	for i, p := range parts {
		camelParts[i] = snakeToCamel(p)
	}
	return mappingField{
		fieldName: snakeToCamel(string(field.Desc.Name())),
		rawPath:   rawPath,
		pathParts: camelParts,
		isSource:  isSource,
	}
}

// transformFuncName returns the transform function name: first char lowercased.
func transformFuncName(messageName string) string {
	if messageName == "" {
		return ""
	}
	runes := []rune(messageName)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

// buildExtraction builds the Luau expression for reading a source field.
// 2-segment: input.table and input.table.field or nil
// 3-segment: input.table and input.table.parent and input.table.parent.valueSubFields and input.table.parent.valueSubFields.child or nil
func buildExtraction(pathParts []string) string {
	if len(pathParts) == 2 {
		// table.field
		table := pathParts[0]
		field := pathParts[1]
		return "input." + table + " and input." + table + "." + field + " or nil"
	}
	if len(pathParts) == 3 {
		// table.parent.child  →  input.table.parent.valueSubFields.child
		table := pathParts[0]
		parent := pathParts[1]
		child := pathParts[2]
		prefix := "input." + table
		return prefix + " and " +
			prefix + "." + parent + " and " +
			prefix + "." + parent + ".valueSubFields and " +
			prefix + "." + parent + ".valueSubFields." + child + " or nil"
	}
	// fallback: just chain them all
	var parts []string
	acc := "input"
	for _, p := range pathParts {
		acc += "." + p
		parts = append(parts, acc)
	}
	return strings.Join(parts, " and ") + " or nil"
}

// buildTargetAccess builds the Luau expression for writing a target field.
// e.g. ["target", "sfSomeField"] → "output.target.sfSomeField"
func buildTargetAccess(pathParts []string) string {
	return "output." + strings.Join(pathParts, ".")
}

// tracePathStr builds the trace path string (e.g. "master.someField").
// For 3-segment compound paths, inserts "valueSubFields" between parent and child.
func tracePathStr(pathParts []string) string {
	if len(pathParts) == 3 {
		return pathParts[0] + "." + pathParts[1] + ".valueSubFields." + pathParts[2]
	}
	return strings.Join(pathParts, ".")
}

// generateMapping is the main entry point for the mapping generator.
func generateMapping(plugin *protogen.Plugin, file *protogen.File) {
	protoPath := file.Desc.Path()
	baseName := strings.TrimSuffix(path.Base(protoPath), ".proto")

	rules := parseMappingRules(file)
	if len(rules) == 0 {
		return
	}

	// Derive the transforms require path from the base name
	transformsModule := strings.Replace(baseName, "_mappings", "_transforms", 1)
	transformsRequire := "@lib/" + transformsModule

	// Determine which rules are multi-output (for types file)
	var multiOutputRules []mappingRule
	for _, rule := range rules {
		if len(rule.targets) > 1 {
			multiOutputRules = append(multiOutputRules, rule)
		}
	}

	// === Types file (only if there are multi-output rules) ===
	if len(multiOutputRules) > 0 {
		gt := plugin.NewGeneratedFile(baseName+"_types.luau", "")
		gt.P("-- GENERATED by protoc-gen-luau \u2014 DO NOT EDIT")
		gt.P("--!strict")
		gt.P(`local DataTypes = require("@lib/data_types")`)
		gt.P()
		gt.P("local Types = {}")
		gt.P()

		for _, rule := range multiOutputRules {
			typeName := rule.messageName + "Output"
			gt.P("export type ", typeName, " = {")
			for _, t := range rule.targets {
				gt.P("\t", t.fieldName, ": DataTypes.StringType?,")
			}
			gt.P("}")
			gt.P()
		}

		gt.P("return Types")
	}

	// === Generated file ===
	g := plugin.NewGeneratedFile(baseName+"_generated.luau", "")
	g.P("-- GENERATED by protoc-gen-luau \u2014 DO NOT EDIT")
	g.P("--!strict")
	g.P(`local DataTypes = require("@lib/data_types")`)
	g.P(`local SourceTables = require("@lib/source_tables")`)
	g.P(`local TargetTables = require("@lib/target_tables")`)
	g.P(`local Transforms = require("`, transformsRequire, `")`)
	g.P()
	g.P("local Generated = {}")
	g.P()

	// === Static trace metadata ===
	g.P("-- Static trace metadata")
	g.P("Generated.mappingTrace = {")
	for _, rule := range rules {
		g.P("\t", rule.messageName, " = {")
		g.P("\t\treads = {")
		for _, s := range rule.sources {
			g.P("\t\t\t\"", tracePathStr(s.pathParts), "\",")
		}
		g.P("\t\t},")
		g.P("\t\twrites = {")
		for _, t := range rule.targets {
			g.P("\t\t\t\"", tracePathStr(t.pathParts), "\",")
		}
		g.P("\t\t},")
		g.P("\t},")
	}
	g.P("}")
	g.P()

	// === Glue functions ===
	for _, rule := range rules {
		emitGlueFunction(g, rule)
	}

	// === runAll ===
	g.P("function Generated.runAll(input: SourceTables.SourceTablesType, output: TargetTables.TargetTablesType)")
	for _, rule := range rules {
		g.P("\tGenerated.run", rule.messageName, "(input, output)")
	}
	g.P("end")
	g.P()
	g.P("return Generated")
}

// emitGlueFunction emits a single glue function for a mapping rule.
func emitGlueFunction(g *protogen.GeneratedFile, rule mappingRule) {
	isMulti := len(rule.targets) > 1
	if isMulti {
		g.P("-- Multi output glue")
	} else {
		g.P("-- Single output glue")
	}
	g.P("function Generated.run", rule.messageName, "(input: SourceTables.SourceTablesType, output: TargetTables.TargetTablesType)")

	// Local variables for source extractions
	for _, s := range rule.sources {
		g.P("\tlocal ", s.fieldName, " = ", buildExtraction(s.pathParts))
	}
	g.P()

	// Build param list for transform call
	var paramNames []string
	for _, s := range rule.sources {
		paramNames = append(paramNames, s.fieldName)
	}
	funcName := transformFuncName(rule.messageName)

	if isMulti {
		// Multi-output: call returns a result struct
		g.P("\tlocal result = Transforms.", funcName, "(", strings.Join(paramNames, ", "), ")")
		for _, t := range rule.targets {
			targetAccess := buildTargetAccess(t.pathParts)
			g.P("\tif result.", t.fieldName, " ~= nil then ", targetAccess, " = result.", t.fieldName, " end")
		}
	} else if len(rule.targets) == 1 {
		// Single-output: call returns a value directly
		t := rule.targets[0]
		targetAccess := buildTargetAccess(t.pathParts)
		g.P("\tlocal ", t.fieldName, " = Transforms.", funcName, "(", strings.Join(paramNames, ", "), ")")
		g.P("\tif ", t.fieldName, " ~= nil then")
		g.P("\t\t", targetAccess, " = ", t.fieldName)
		g.P("\tend")
	}

	g.P("end")
	g.P()
}
