package main

import (
	"path"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

func generate(plugin *protogen.Plugin) error {
	for _, f := range plugin.Files {
		if !f.Generate {
			continue
		}
		protoPath := f.Desc.Path()
		luauName := strings.TrimSuffix(path.Base(protoPath), ".proto") + ".luau"

		g := plugin.NewGeneratedFile(luauName, "")
		g.P("--!strict")
		g.P("-- Generated by protoc-gen-luau from ", protoPath)
		g.P("return {}")
	}
	return nil
}
