package main

import (
	"path"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

func generate(plugin *protogen.Plugin) error {
	for _, f := range plugin.Files {
		if !f.Generate {
			continue
		}
		protoPath := f.Desc.Path()
		baseName := strings.TrimSuffix(path.Base(protoPath), ".proto")

		if baseName == "data_types" {
			generateDataTypes(plugin, f)
			continue
		}

		if baseName == "table_schema" {
			generateTableSchema(plugin, f)
			continue
		}

		luauName := baseName + ".luau"
		g := plugin.NewGeneratedFile(luauName, "")
		g.P("--!strict")
		g.P("-- Generated by protoc-gen-luau from ", protoPath)
		g.P("return {}")
	}
	return nil
}
