package main

import (
	"os"
	"testing"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

func TestGenerate(t *testing.T) {
	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{
			"data_types.proto",
			"table_schema.proto",
			"tables/source_table.proto",
			"tables/target_table.proto",
		},
		ProtoFile: []*descriptorpb.FileDescriptorProto{
			{Name: proto.String("data_types.proto"), Syntax: proto.String("proto3"),
				Options: &descriptorpb.FileOptions{GoPackage: proto.String("protoc-gen-luau/gen/datatypes;datatypes")}},
			{Name: proto.String("table_schema.proto"), Syntax: proto.String("proto3"),
				Dependency: []string{"data_types.proto"},
				Options:    &descriptorpb.FileOptions{GoPackage: proto.String("protoc-gen-luau/gen/tableschema;tableschema")}},
			{Name: proto.String("tables/source_table.proto"), Syntax: proto.String("proto3"),
				Dependency: []string{"data_types.proto"},
				Options:    &descriptorpb.FileOptions{GoPackage: proto.String("protoc-gen-luau/gen/tables/source;source")}},
			{Name: proto.String("tables/target_table.proto"), Syntax: proto.String("proto3"),
				Dependency: []string{"data_types.proto"},
				Options:    &descriptorpb.FileOptions{GoPackage: proto.String("protoc-gen-luau/gen/tables/target;target")}},
		},
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen.New: %v", err)
	}

	if err := generate(plugin); err != nil {
		t.Fatalf("generate: %v", err)
	}

	resp := plugin.Response()
	if resp.GetError() != "" {
		t.Fatalf("plugin error: %s", resp.GetError())
	}

	wantFiles := map[string]string{
		"data_types.luau":   "--!strict\n-- Generated by protoc-gen-luau from data_types.proto\nreturn {}\n",
		"table_schema.luau": "--!strict\n-- Generated by protoc-gen-luau from table_schema.proto\nreturn {}\n",
		"source_table.luau": "--!strict\n-- Generated by protoc-gen-luau from tables/source_table.proto\nreturn {}\n",
		"target_table.luau": "--!strict\n-- Generated by protoc-gen-luau from tables/target_table.proto\nreturn {}\n",
	}

	gotFiles := make(map[string]string)
	for _, f := range resp.File {
		gotFiles[f.GetName()] = f.GetContent()
	}

	if len(gotFiles) != len(wantFiles) {
		t.Errorf("got %d files, want %d", len(gotFiles), len(wantFiles))
	}

	for name, want := range wantFiles {
		got, ok := gotFiles[name]
		if !ok {
			t.Errorf("missing output file %q", name)
			continue
		}
		if got != want {
			t.Errorf("file %q:\ngot:\n%s\nwant:\n%s", name, got, want)
		}
	}
}

func TestGenerateGolden(t *testing.T) {
	data, err := os.ReadFile("testdata/request.pb")
	if err != nil {
		t.Fatalf("reading request.pb: %v", err)
	}

	req := &pluginpb.CodeGeneratorRequest{}
	if err := proto.Unmarshal(data, req); err != nil {
		t.Fatalf("unmarshaling request: %v", err)
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen.New: %v", err)
	}

	if err := generate(plugin); err != nil {
		t.Fatalf("generate: %v", err)
	}

	resp := plugin.Response()
	if resp.GetError() != "" {
		t.Fatalf("plugin error: %s", resp.GetError())
	}

	if got, want := len(resp.File), 4; got != want {
		t.Errorf("got %d output files, want %d", got, want)
	}

	for _, f := range resp.File {
		goldenPath := "testdata/golden/" + f.GetName()
		want, err := os.ReadFile(goldenPath)
		if err != nil {
			t.Errorf("reading golden %s: %v", goldenPath, err)
			continue
		}
		if f.GetContent() != string(want) {
			t.Errorf("file %s differs from golden:\ngot:\n%s\nwant:\n%s",
				f.GetName(), f.GetContent(), string(want))
		}
	}
}
